Bump core-foundation to 0.9
mullvad/system-configuration-rs pull request #29
Opened 2021-09-08 15:29 UTC by pinkisemils

This is a feeble attempt at bumping the version of core-foundation and core-foundation-sys in hopes of reducing crashes in the offline monitor.

2021-09-09 07:34 UTC, faern requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/29)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[.travis.yml, line 7 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/29#-Mj8SfKX867H0WOHxGZx:-Mj8SfKY7HuoRvcfmeJt:bf5y4zq) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/14aab5641d128694d2e5481e3122d63c1faefc33/.travis.yml#L7)):*
> ```YAML
>   - beta
>   - nightly
>   - 1.46.0
> ```

If we bump the MSRV please mention that in the changelog.
___
*[system-configuration-sys/Cargo.toml, line 3 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/29#-Mj8T3aG8FhUuT4Rnu9B:-Mj8T3aG8FhUuT4Rnu9C:bhx0zkv) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/14aab5641d128694d2e5481e3122d63c1faefc33/system-configuration-sys/Cargo.toml#L3)):*
> ```TOML
> [package]
> name = "system-configuration-sys"
> version = "0.4.2"
> ```

We publicly re-export the `core-foundation-sys` dependency. So this is changing the public API. As such, this needs to be bumped to `0.5.0`. https://github.com/mullvad/system-configuration-rs/blob/master/system-configuration-sys/src/lib.rs#L20

The same goes for the parent crate `system-configuration`.


<!-- Sent from Reviewable.io -->

2021-12-30 00:16 UTC, dvc94ch commented
@pinkisemils any plans to finish this? looks like the most advanced "bump core-foundation" PR.

2021-12-30 16:24 UTC, faern commented
@dvc94ch This was put on hold since we did not need these changes. But maybe we should go ahead with this anyway, to help the ecosystem move towards newer core-foundation.

2022-01-03 08:33 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/29)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[.travis.yml, line 7 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/29#-Mj8SfKX867H0WOHxGZx:-MsU3C56CZX8Gjfl05o6:b-lg0jue) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/14aab5641d128694d2e5481e3122d63c1faefc33/.travis.yml#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If we bump the MSRV please mention that in the changelog.
</blockquote></details>

Closing this as it's being done in #31 
___
*[system-configuration/Cargo.toml, line 3 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/29#-MsU3Kct-KE00gMVzzx4:-MsU3Kct-KE00gMVzzx5:bwpddrp) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/14aab5641d128694d2e5481e3122d63c1faefc33/system-configuration/Cargo.toml#L3)):*
> ```TOML
> [package]
> name = "system-configuration"
> version = "0.4.1"
> ```

Can we remove the version bumps from this PR? We'll focus this PR on the dependency upgrade and then releasing is something unrelated to code changes if possible.


<!-- Sent from Reviewable.io -->

2022-01-03 11:07 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/29)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @faern and @pinkisemils)

___
*[system-configuration/Cargo.toml, line 3 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/29#-MsU3Kct-KE00gMVzzx4:-MsUbwDX0VvQPKKKoFuT:bhy9ost) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/14aab5641d128694d2e5481e3122d63c1faefc33/system-configuration/Cargo.toml#L3)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we remove the version bumps from this PR? We'll focus this PR on the dependency upgrade and then releasing is something unrelated to code changes if possible.
</blockquote></details>

Will do!


<!-- Sent from Reviewable.io -->

2022-01-03 12:30 UTC, dvc94ch approved these changes

2022-01-03 12:30 UTC, dvc94ch commented on system-configuration-sys/Cargo.toml
> +version = "0.4.2"
I guess this version bump should go too?

2022-01-03 13:34 UTC, faern approved these changes
Reviewable is messing with me. Approving here instead.
Optimal would be to add the upgrade to the changelog here. But otherwise I'll just add it when doing the release.
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

2022-01-03 13:39 UTC, merged