Add SCNetworkService and SCNetworkSet
mullvad/system-configuration-rs pull request #37
Opened 2023-01-27 22:48 UTC by pinkisemils

To aid with finding the best default route, I'm planning on relying on the user defined network service order. To do this, I need to add some wrappers for the FFI code to fetch it from the system configuration. 

The changes are fairly plain, and whilst there is a test, which aided in development but I'm not sure if it's worthwhile to have around.

Oh, and it seems like clippy is failing with an ICE :facepalm:

2023-01-29 15:15 UTC, pronebird requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: all files reviewed, 4 unresolved discussions (waiting on @pinkisemils)

___
*[`system-configuration/src/network_configuration.rs` line 228 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy1qBU--HJAzFLC0QY:-NMy1qBU--HJAzFLC0QZ:bazf0v9) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L228)):*
> ```XML
>             // SCNetworkSerivceCopyAll will always return a valid pointer, and
>             // T::wrap_under_create_rule will panic if the pointer is nil.
>             CFArray::<Self>::wrap_under_create_rule(array_ptr)
> ```

Note that `SCNetworkServiceCopyAll()` is marked as returning `CFArray?` in Swift. Based on source code it can return `NULL` if the underlying `SCPreferences` key does not exist in registry or it's corrupt:

```c
path = SCPreferencesPathKeyCreateNetworkServices(NULL);
services = SCPreferencesPathGetValue(prefs, path);
CFRelease(path);

if ((services != NULL) && !isA_CFDictionary(services)) {
    return NULL;
}
```

Not sure it would make sense to return `Option<CFArray<Self>>` but returning empty array in that case is probably reasonable.

https://developer.apple.com/documentation/systemconfiguration/1516810-scnetworkservicecopyall
https://opensource.apple.com/source/configd/configd-699.30.1/SystemConfiguration.fproj/SCNetworkService.c.auto.html
___
*[`system-configuration/src/network_configuration.rs` line 234 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy4NfZAo7Ub4QGdXhh:-NMy4NfZAo7Ub4QGdXhi:bm2ap6g) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L234)):*
> ```XML
>     /// Returns true if the network service is currently enabled
>     pub fn enabled(&self) -> bool {
>         // SAFETY: Call to SCNetworkServiceGetEnabled is safe since the pointer SCNetworkService is
> ```

Seems a bit redundant to comment on safety so much. If you look at `SCNetworkInterface`, all of the methods there follow the same pattern but without safety comments on every line. It could be that this particular principle of commenting on unsafe code was adopted much further in time, however it adds quite a bit of noise to the codebase especially where everything is inherently unsafe, i.e FFI & C interop.
___
*[`system-configuration/src/network_configuration.rs` line 243 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy2DWd7Wlr2NNyLAGa:-NMy2DWd7Wlr2NNyLAGb:b-1krrvj) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L243)):*
> ```XML
>         unsafe {
>             // SAFETY: Call to SCNetworkServiceGetInterface is safe since pointer to
>             // SCNetorkService is valid for the lifetime of this object.
> ```

Typo in `SCNetworkService`.
___
*[`system-configuration/src/network_configuration.rs` line 296 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy2KOYAjdL963szKu5:-NMy2KOYAjdL963szKu6:bngujd1) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L296)):*
> ```XML
>     pub fn service_order(&self) -> CFArray<CFString> {
>         // SAFETY: SCNetworkSetGetServiceOrder is safe to call with self.0 since the pointer is
>         // valid for the lifetime of the objet, and constructing the CFArray is safe regardless of
> ```

Typo in `object`


<!-- Sent from Reviewable.io -->

2023-01-30 10:56 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pronebird)

___
*[`system-configuration/src/network_configuration.rs` line 228 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy1qBU--HJAzFLC0QY:-NN0v37W73iVYGZLd0zz:b-jeq3un) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L228)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Note that `SCNetworkServiceCopyAll()` is marked as returning `CFArray?` in Swift. Based on source code it can return `NULL` if the underlying `SCPreferences` key does not exist in registry or it's corrupt:

```c
path = SCPreferencesPathKeyCreateNetworkServices(NULL);
services = SCPreferencesPathGetValue(prefs, path);
CFRelease(path);

if ((services != NULL) && !isA_CFDictionary(services)) {
    return NULL;
}
```

Not sure it would make sense to return `Option<CFArray<Self>>` but returning empty array in that case is probably reasonable.

https://developer.apple.com/documentation/systemconfiguration/1516810-scnetworkservicecopyall
https://opensource.apple.com/source/configd/configd-699.30.1/SystemConfiguration.fproj/SCNetworkService.c.auto.html
</blockquote></details>

Returning an empty array is a bit of a hassle, but I've made it work. 
___
*[`system-configuration/src/network_configuration.rs` line 234 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy4NfZAo7Ub4QGdXhh:-NN15_LQBC3Qn1_1Nvyq:b-9qtsbn) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L234)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Seems a bit redundant to comment on safety so much. If you look at `SCNetworkInterface`, all of the methods there follow the same pattern but without safety comments on every line. It could be that this particular principle of commenting on unsafe code was adopted much further in time, however it adds quite a bit of noise to the codebase especially where everything is inherently unsafe, i.e FFI & C interop.
</blockquote></details>

It's a bit of a carryover from the other rust codebases and it's considered good practice. If you feel strongly about this, I'll remove these.


<!-- Sent from Reviewable.io -->

2023-01-30 14:08 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`system-configuration/src/network_configuration.rs` line 234 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy4NfZAo7Ub4QGdXhh:-NN1zvYZ2bq2pPwT9nSh:b-qu2y7g) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L234)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It's a bit of a carryover from the other rust codebases and it's considered good practice. If you feel strongly about this, I'll remove these.
</blockquote></details>

Lotta noise for my taste but I am not the one to change internal rules.


<!-- Sent from Reviewable.io -->

2023-01-30 16:44 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-:-NN2ZEn9DPWdi1OaD0YI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils and @pronebird)



<!-- Sent from Reviewable.io -->

2023-01-31 10:03 UTC, pinkisemils reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @faern and @pronebird)

___
*[`system-configuration/src/network_configuration.rs` line 234 at r1](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NMy4NfZAo7Ub4QGdXhh:-NN6GlVXCmfswsc1Pc6B:b3csaum) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/529a8ce3eb3c053c78c5f59e935fb2c7eca4beff/system-configuration/src/network_configuration.rs#L234)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Lotta noise for my taste but I am not the one to change internal rules.
</blockquote></details>

I've removed them now.


<!-- Sent from Reviewable.io -->

2023-02-01 10:38 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-01 10:38 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-:-NNBYhKfE1scBrJDVJYd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-01 12:48 UTC, faern approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: all files reviewed, 1 unresolved discussion (waiting on @pinkisemils)

___
*[`CHANGELOG.md` line 26 at r5](https://reviewable.io/reviews/mullvad/system-configuration-rs/37#-NNC0F0o31XgxuV0AIIE:-NNC0F0p0HSV8Mr3aHwc:b-jyitig) ([raw file](https://github.com/mullvad/system-configuration-rs/blob/71bed815f49372d087870dc76dc091093a2b1466/CHANGELOG.md#L26)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - Added bindings for `SCNetworkSet` and `SCNetworkService`
> ```

Nit: `Add ...` for imperative form


<!-- Sent from Reviewable.io -->

2023-02-01 12:50 UTC, faern approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/system-configuration-rs/37)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-01 12:57 UTC, merged